version: '3'

services:
  postgres-compose:
    image: postgis/postgis:12-2.5-alpine
    environment:
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "15432:5432"
    volumes:
      - ./container-data/postgres-data:/var/lib/postgresql/data 

  maria-db:
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: "mariadb"
    ports:
      - "3306:3306"
    volumes:
      - ./container-data/mariadb-data:/var/lib/mysql
      
  # pgadmin-compose:
  #   image: dpage/pgadmin4
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: "user@user.com.br"
  #     PGADMIN_DEFAULT_PASSWORD: "postgres"
  #   ports:
  #     - "16543:80"
  #   volumes:
  #     - ./container-data/pgadmin:/root/.pgadmin
  #   depends_on:
  #     - postgres-compose